// Mesa Vista Pharmacy — the fictional, resettable demo tenant.
//
// Everything here is invented: three Nevada locations, fifteen staff with
// @mesavistarx.com addresses (a domain that receives no mail), six weeks of
// schedule anchored to the Monday of the CURRENT week at runtime, one
// engine-real deficiency story, and compliance snapshots generated by the
// same engine the app uses.
//
// The deficiency story (current week, Thursday, Henderson): Dr. Sunita
// Patel left at 2:00 PM on a family emergency and the float pharmacist,
// Dr. Owen Fitzgerald, was held up at Spring Valley until 4:00 PM — so
// from 2:00–4:00 the technicians kept the counter open with no pharmacist
// on duty. The ratio engine flags exactly those slots deficient; one
// isolated day, so no 3-consecutive-day board trigger.
//
// Shared by scripts/seed-mesa-vista.ts (CLI) and the admin console's
// "Restore demo data" action — so it deliberately has NO "server-only"
// import and uses relative paths (tsx-friendly).

import type { SupabaseClient } from "@supabase/supabase-js";
import { addDaysStr, eachDate, nowInTimeZone } from "../dates";
import { evaluateZone } from "../engine/ratio";
import { generateComplianceRecord } from "../engine/compliance";
import type { EngineSegment } from "../engine/types";

export const MESA_VISTA_NAME = "Mesa Vista Pharmacy";
export const FRANK_EMAIL = "frank@mesavistarx.com";
export const DEMO_LOGIN_ALIAS = "demo@rxshift.io";

/**
 * Staff-linked demo logins, so a demo can be DRIVEN as a real person
 * (My Schedule, requests, live-status) instead of as a disembodied
 * owner. The auth emails are fictional (nobody can sign in directly);
 * the @rxshift.io aliases deliver their magic links to the catch-all
 * inbox. Re-linked to their staff records on every reset.
 */
const DEMO_LOGINS: {
  staffName: string;
  alias: string;
  role: "owner_admin" | "scheduler" | "supervisor" | "read_only" | "staff";
}[] = [
  // Jamison's demo identity — a tech's-eye view of the app
  { staffName: "Jerome Williams", alias: "jerome@rxshift.io", role: "staff" },
  // Susie's demo identity — the Managing Pharmacist (her real-life role)
  { staffName: "Dr. Patricia Nguyen", alias: "patricia@rxshift.io", role: "scheduler" },
];

const TZ = "America/Los_Angeles";
const WEEK_OFFSETS = [-4, -3, -2, -1, 0, 1, 2]; // 4 past, current, 2 future

type Ratio = "pharmacist" | "technician" | "non_counting";

interface Person {
  name: string;
  title: string;
  ratio: Ratio;
  location: "SV" | "HD" | "NLV";
}

const ROSTER: Person[] = [
  // Spring Valley — flagship, fully compliant
  { name: "Dr. Patricia Nguyen", title: "Managing Pharmacist / PIC", ratio: "pharmacist", location: "SV" },
  { name: "Dr. Marcus Webb", title: "Staff Pharmacist", ratio: "pharmacist", location: "SV" },
  { name: "Dr. Lena Park", title: "Staff Pharmacist", ratio: "pharmacist", location: "SV" },
  { name: "Carlos Rivera", title: "Lead Certified Tech (CPhT)", ratio: "technician", location: "SV" },
  { name: "Ashley Morales", title: "Certified Tech (CPhT)", ratio: "technician", location: "SV" },
  { name: "Dana Holt", title: "Certified Tech (CPhT)", ratio: "technician", location: "SV" },
  { name: "Tyler Brooks", title: "Pharmacy Trainee", ratio: "technician", location: "SV" },
  // Henderson — the deficiency-story location
  { name: "Dr. Sunita Patel", title: "Staff Pharmacist", ratio: "pharmacist", location: "HD" },
  { name: "Dr. Owen Fitzgerald", title: "Float Pharmacist (SV / Henderson)", ratio: "pharmacist", location: "HD" },
  { name: "Jerome Williams", title: "Certified Tech (CPhT)", ratio: "technician", location: "HD" },
  { name: "Keisha Brown", title: "Certified Tech (CPhT)", ratio: "technician", location: "HD" },
  { name: "Miguel Santos", title: "Pharmacy Trainee", ratio: "technician", location: "HD" },
  // North Las Vegas — newest, smallest, compliant
  { name: "Dr. Kevin Chang", title: "Staff Pharmacist", ratio: "pharmacist", location: "NLV" },
  { name: "Rachel Odom", title: "Certified Tech (CPhT)", ratio: "technician", location: "NLV" },
  { name: "Destiny Freeman", title: "Certified Tech (CPhT)", ratio: "technician", location: "NLV" },
];

function fictionalEmail(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/^dr\.\s*/, "")
      .replace(/[^a-z\s]/g, "")
      .trim()
      .replace(/\s+/g, ".") + "@mesavistarx.com"
  );
}

/** One recurring shift line: which weekdays (1=Mon..6=Sat), what hours. */
interface ShiftLine {
  staff: string;
  days: number[];
  start: string;
  end: string;
  breakMin: number;
  workType?: string; // default = none (counts by ratio_type)
}

const SV_LINES: ShiftLine[] = [
  { staff: "Dr. Patricia Nguyen", days: [1, 2, 3, 4, 5], start: "09:00", end: "17:00", breakMin: 30 },
  { staff: "Dr. Marcus Webb", days: [1, 2, 3, 4, 5], start: "11:00", end: "19:00", breakMin: 30 },
  { staff: "Dr. Marcus Webb", days: [6], start: "09:00", end: "17:00", breakMin: 30 },
  // A third pharmacist gives Spring Valley genuine ratio headroom — so the
  // "who can step away?" feature has a positive story to show (and the live
  // demo demonstrates it).
  { staff: "Dr. Lena Park", days: [1, 2, 3, 4, 5], start: "09:00", end: "19:00", breakMin: 30 },
  { staff: "Carlos Rivera", days: [1, 2, 3, 4, 5], start: "09:00", end: "17:00", breakMin: 30 },
  { staff: "Carlos Rivera", days: [6], start: "09:00", end: "15:00", breakMin: 30 },
  { staff: "Ashley Morales", days: [1, 2, 3, 4, 5], start: "09:00", end: "16:30", breakMin: 30 },
  { staff: "Dana Holt", days: [1, 2, 3, 4, 5], start: "11:00", end: "19:00", breakMin: 30 },
  { staff: "Dana Holt", days: [6], start: "11:00", end: "17:00", breakMin: 30 },
  { staff: "Tyler Brooks", days: [2, 3, 4], start: "10:00", end: "16:00", breakMin: 30, workType: "Training" },
];

const HD_LINES: ShiftLine[] = [
  { staff: "Dr. Sunita Patel", days: [1, 2, 3, 4, 5], start: "09:00", end: "17:00", breakMin: 30 },
  { staff: "Dr. Sunita Patel", days: [6], start: "09:00", end: "15:00", breakMin: 30 },
  { staff: "Dr. Owen Fitzgerald", days: [1, 3, 4, 5], start: "14:00", end: "19:00", breakMin: 0 },
  { staff: "Jerome Williams", days: [1, 2, 3, 4, 5], start: "09:00", end: "17:00", breakMin: 30 },
  { staff: "Jerome Williams", days: [6], start: "09:00", end: "15:00", breakMin: 30 },
  { staff: "Keisha Brown", days: [1, 3, 4, 5], start: "11:00", end: "19:00", breakMin: 30 },
  { staff: "Keisha Brown", days: [2], start: "09:00", end: "17:00", breakMin: 30 },
  { staff: "Miguel Santos", days: [1, 2, 3, 4, 5], start: "10:00", end: "16:00", breakMin: 30, workType: "Training" },
];

const NLV_LINES: ShiftLine[] = [
  { staff: "Dr. Kevin Chang", days: [1, 2, 3, 4, 5], start: "09:00", end: "17:00", breakMin: 30 },
  { staff: "Dr. Kevin Chang", days: [6], start: "09:00", end: "13:00", breakMin: 0 },
  { staff: "Rachel Odom", days: [1, 2, 3, 4, 5], start: "09:00", end: "17:00", breakMin: 30 },
  { staff: "Rachel Odom", days: [6], start: "09:00", end: "13:00", breakMin: 0 },
  { staff: "Destiny Freeman", days: [1, 2, 3, 4, 5], start: "10:00", end: "16:00", breakMin: 30 },
];

const WORK_TYPES = [
  { name: "Dispensing", counts_as: "technician", counting_default: true, is_specialized: false, color: "#3B6EA5" },
  { name: "Training", counts_as: "technician", counting_default: true, is_specialized: false, color: "#2BA39A" },
  { name: "Inventory", counts_as: "technician", counting_default: false, is_specialized: false, color: "#5B6B82" },
  { name: "Meeting", counts_as: "none", counting_default: false, is_specialized: false, color: "#6A5ACD" },
];

// Departments — tenant-level area tags on a shift (organize + filter; they do
// NOT affect the ratio, unlike work types). Gives the department filter on the
// schedule something real to show.
const DEPARTMENTS = ["Retail Counter", "Compounding", "Specialty", "Drive-Thru"];

// Which department each person works in (default = Retail Counter). Spread so a
// manager filtering by department sees a meaningful, varied roster.
const STAFF_DEPARTMENT: Record<string, string> = {
  "Dr. Marcus Webb": "Compounding",
  "Dana Holt": "Compounding",
  "Dr. Lena Park": "Specialty",
  "Tyler Brooks": "Specialty",
  "Keisha Brown": "Drive-Thru",
  "Miguel Santos": "Drive-Thru",
};

/** Monday of the current week in the demo tenant's timezone. */
export function currentWeekMonday(): string {
  const { date } = nowInTimeZone(TZ);
  const dow = new Date(`${date}T00:00:00Z`).getUTCDay();
  return addDaysStr(date, dow === 0 ? -6 : 1 - dow);
}

function weekday(date: string): number {
  return new Date(`${date}T00:00:00Z`).getUTCDay();
}

type Log = (msg: string) => void;

/** Delete all DATA for the tenant; keep the tenant row and Frank's account. */
export async function clearMesaVistaData(
  service: SupabaseClient,
  tenantId: string,
  log: Log = () => {}
): Promise<void> {
  // FK-safe order; shift_segment cascades from shift
  const tables = [
    "compliance_snapshot",
    "override_log",
    "activity_log_note",
    "activity_log",
    "notification",
    "live_status",
    "swap_request",
    "callout",
    "time_off_request",
    "shift",
    "schedule_period",
    "constraint_rule",
    "staff_location",
    "staff",
    "department",
    "location",
    "ratio_rule",
    "work_type",
  ];
  for (const table of tables) {
    const { error } = await service.from(table).delete().eq("tenant_id", tenantId);
    if (error) throw new Error(`clear ${table}: ${error.message}`);
  }
  log("Cleared existing Mesa Vista data (tenant + demo login preserved).");
}

/** Find-or-create the tenant row. Returns its id. */
async function ensureTenant(service: SupabaseClient, log: Log): Promise<string> {
  const { data: existing } = await service
    .from("tenant")
    .select("id")
    .eq("name", MESA_VISTA_NAME)
    .maybeSingle();
  if (existing) return existing.id;

  const { data: tenant, error } = await service
    .from("tenant")
    .insert({
      name: MESA_VISTA_NAME,
      timezone: TZ,
      schedule_cycle: "weekly",
      ratio_slot_minutes: 30,
      has_ratio: true,
      onboarding_complete: true,
      status: "trial",
      is_demo: true, // the email gate: redirect when set, otherwise silent
      outbound_email_enabled: true,
      default_break_minutes: 30,
    })
    .select("id")
    .single();
  if (error) throw new Error(`tenant insert: ${error.message}`);
  log(`Created tenant "${MESA_VISTA_NAME}" (demo mode).`);
  return tenant.id;
}

/** Frank DiMaggio — the demo owner login. staff_id stays NULL so resets
 *  can wipe the whole roster without touching his account. */
async function ensureFrank(
  service: SupabaseClient,
  tenantId: string,
  log: Log
): Promise<string> {
  let authUserId: string | null = null;
  const { data: list } = await service.auth.admin.listUsers({ page: 1, perPage: 1000 });
  authUserId = list?.users.find((u) => u.email === FRANK_EMAIL)?.id ?? null;
  if (!authUserId) {
    const { data, error } = await service.auth.admin.createUser({
      email: FRANK_EMAIL,
      email_confirm: true,
    });
    if (error) throw new Error(`Frank auth user: ${error.message}`);
    authUserId = data.user.id;
    log(`Created auth user ${FRANK_EMAIL}.`);
  }

  const { data: appUser } = await service
    .from("app_user")
    .select("id")
    .eq("supabase_user_id", authUserId)
    .maybeSingle();
  let appUserId = appUser?.id as string | undefined;
  if (!appUserId) {
    const { data, error } = await service
      .from("app_user")
      .insert({
        supabase_user_id: authUserId,
        staff_id: null,
        tenant_id: tenantId,
        role: "owner_admin",
        is_pto_approver: true,
        pto_approver_rank: "primary",
      })
      .select("id")
      .single();
    if (error) throw new Error(`Frank app_user: ${error.message}`);
    appUserId = data.id;
    log("Created Frank DiMaggio (owner_admin, no staff record).");
  }

  // Frank has no staff record, so the override log / compliance record can't
  // resolve his name from staff.full_name — give his app_user a display name so
  // the "who" reads "Frank DiMaggio" instead of the raw role. Set on every run
  // (idempotent) so a reset, which preserves Frank's app_user, still applies it.
  await service
    .from("app_user")
    .update({ display_name: "Frank DiMaggio" })
    .eq("id", appUserId);

  // Sign-in path for real humans: typing demo@rxshift.io at /app/login
  // delivers Frank's magic link to that address (the rxshift.io catch-all).
  const { data: alias } = await service
    .from("login_alias")
    .select("alias_email")
    .eq("alias_email", DEMO_LOGIN_ALIAS)
    .maybeSingle();
  if (!alias) {
    const { error } = await service
      .from("login_alias")
      .insert({ alias_email: DEMO_LOGIN_ALIAS, app_user_id: appUserId });
    if (error) throw new Error(`demo alias: ${error.message}`);
    log(`Login alias ${DEMO_LOGIN_ALIAS} → Frank.`);
  }

  return authUserId;
}

/** Create-or-relink the staff-linked demo logins (Jerome, Dr. Nguyen).
 *  app_user.staff_id is ON DELETE SET NULL, so after a reset wipes the
 *  roster these accounts survive unlinked — we re-point them at the
 *  freshly seeded staff rows by name. */
async function ensureDemoLogins(
  service: SupabaseClient,
  tenantId: string,
  staffIds: Map<string, string>,
  log: Log
): Promise<void> {
  const { data: list } = await service.auth.admin.listUsers({ page: 1, perPage: 1000 });

  for (const login of DEMO_LOGINS) {
    const staffId = staffIds.get(login.staffName);
    if (!staffId) continue;
    const authEmail = fictionalEmail(login.staffName);

    let authUserId = list?.users.find((u) => u.email === authEmail)?.id ?? null;
    if (!authUserId) {
      const { data, error } = await service.auth.admin.createUser({
        email: authEmail,
        email_confirm: true,
      });
      if (error) throw new Error(`${login.staffName} auth user: ${error.message}`);
      authUserId = data.user.id;
    }

    const { data: appUser } = await service
      .from("app_user")
      .select("id")
      .eq("supabase_user_id", authUserId)
      .maybeSingle();
    let appUserId = appUser?.id as string | undefined;
    if (appUserId) {
      const { error } = await service
        .from("app_user")
        .update({ staff_id: staffId, role: login.role })
        .eq("id", appUserId);
      if (error) throw new Error(`${login.staffName} relink: ${error.message}`);
    } else {
      const { data, error } = await service
        .from("app_user")
        .insert({
          supabase_user_id: authUserId,
          staff_id: staffId,
          tenant_id: tenantId,
          role: login.role,
          is_pto_approver: login.role !== "staff",
          pto_approver_rank: login.role !== "staff" ? "backup" : null,
        })
        .select("id")
        .single();
      if (error) throw new Error(`${login.staffName} app_user: ${error.message}`);
      appUserId = data.id;
    }

    const { data: alias } = await service
      .from("login_alias")
      .select("alias_email")
      .eq("alias_email", login.alias)
      .maybeSingle();
    if (!alias) {
      const { error } = await service
        .from("login_alias")
        .insert({ alias_email: login.alias, app_user_id: appUserId });
      if (error) throw new Error(`${login.alias}: ${error.message}`);
    }
    log(`Demo login ${login.alias} → ${login.staffName} (${login.role}).`);
  }
}

export interface SeedResult {
  tenantId: string;
  weeks: number;
  shifts: number;
  deficientHours: number;
}

/**
 * Seed (or re-seed after clearMesaVistaData) the full Mesa Vista dataset,
 * date-anchored to the Monday of the current week. Refuses to run if the
 * tenant already has locations — call clearMesaVistaData first to reset.
 */
export async function seedMesaVista(
  service: SupabaseClient,
  log: Log = () => {}
): Promise<SeedResult> {
  const tenantId = await ensureTenant(service, log);
  const frankAuthId = await ensureFrank(service, tenantId, log);

  const { data: existingLoc } = await service
    .from("location")
    .select("id")
    .eq("tenant_id", tenantId)
    .limit(1);
  if (existingLoc && existingLoc.length > 0) {
    throw new Error(
      "Mesa Vista already has data. Run the reset (clears data, keeps the tenant + demo login) instead of seeding twice."
    );
  }

  const anchor = currentWeekMonday();
  log(`Anchoring schedule to current week Monday: ${anchor}`);

  // Ratio rule — Nevada 1:3 (the flat cap today's engine enforces)
  const { data: rule, error: ruleErr } = await service
    .from("ratio_rule")
    .insert({
      tenant_id: tenantId,
      state: "NV",
      max_techs_per_pharmacist: 3,
      source_citation: "NAC 639.250; NRS 639.1371",
      notes: "Nevada non-institutional retail default: 1 pharmacist : 3 technicians.",
    })
    .select("id")
    .single();
  if (ruleErr) throw new Error(ruleErr.message);

  // Locations (ratio is computed per location — no zones)
  const LOCS: { key: "SV" | "HD" | "NLV"; name: string; address: string }[] = [
    { key: "SV", name: "Mesa Vista — Spring Valley", address: "4880 S Rainbow Blvd, Las Vegas, NV" },
    { key: "HD", name: "Mesa Vista — Henderson", address: "2310 W Horizon Ridge Pkwy, Henderson, NV" },
    { key: "NLV", name: "Mesa Vista — North Las Vegas", address: "3175 W Craig Rd, North Las Vegas, NV" },
  ];
  const locIds = new Map<string, string>();
  const locNames = new Map<string, string>();
  for (const loc of LOCS) {
    const { data: row, error } = await service
      .from("location")
      .insert({ tenant_id: tenantId, name: loc.name, address: loc.address })
      .select("id")
      .single();
    if (error) throw new Error(error.message);
    locIds.set(loc.key, row.id);
    locNames.set(loc.key, loc.name);
  }
  log("3 locations.");

  // Work types
  const { data: wtRows, error: wtErr } = await service
    .from("work_type")
    .insert(WORK_TYPES.map((w) => ({ ...w, tenant_id: tenantId })))
    .select("id, name");
  if (wtErr) throw new Error(wtErr.message);
  const wtIds = new Map(wtRows.map((w) => [w.name, w.id]));

  // Departments (tenant-level area tags)
  const { data: deptRows, error: deptErr } = await service
    .from("department")
    .insert(DEPARTMENTS.map((name) => ({ tenant_id: tenantId, name })))
    .select("id, name");
  if (deptErr) throw new Error(deptErr.message);
  const deptIds = new Map(deptRows.map((d) => [d.name, d.id]));
  const deptFor = (staffName: string) =>
    deptIds.get(STAFF_DEPARTMENT[staffName] ?? "Retail Counter") ?? null;
  log(`${deptRows.length} departments.`);

  // Staff — fictional @mesavistarx.com addresses (demo gate guarantees
  // no mail can ever reach them)
  const { data: staffRows, error: stErr } = await service
    .from("staff")
    .insert(
      ROSTER.map((p) => ({
        tenant_id: tenantId,
        home_location_id: locIds.get(p.location)!,
        full_name: p.name,
        login_email: fictionalEmail(p.name),
        work_email: fictionalEmail(p.name),
        job_title: p.title,
        ratio_type: p.ratio,
        employment_type: "full_time",
        certified: p.title.includes("CPhT"),
      }))
    )
    .select("id, full_name");
  if (stErr) throw new Error(stErr.message);
  const staffIds = new Map(staffRows.map((s) => [s.full_name, s.id]));
  log(`${staffRows.length} staff seeded.`);

  await ensureDemoLogins(service, tenantId, staffIds, log);

  // Overtime guardrail (gives the constraint engine something real to watch)
  await service.from("constraint_rule").insert({
    tenant_id: tenantId,
    scope_type: "role",
    scope_id: "technician",
    rule_type: "overtime",
    params: { threshold_hours: 40 },
    effective_start: addDaysStr(anchor, -28),
    active: true,
  });

  // PTO — one approved (next week), one pending (two weeks out)
  const ptoStart = addDaysStr(anchor, 7); // next Monday
  const ptoEnd = addDaysStr(anchor, 8);
  const pendingDay = addDaysStr(anchor, 18); // Friday two weeks out
  await service.from("time_off_request").insert([
    {
      tenant_id: tenantId,
      staff_id: staffIds.get("Ashley Morales")!,
      start_date: ptoStart,
      end_date: ptoEnd,
      type: "pto",
      staff_message: "Long weekend in Utah — back Wednesday.",
      status: "approved",
      decided_at: new Date().toISOString(),
    },
    {
      tenant_id: tenantId,
      staff_id: staffIds.get("Jerome Williams")!,
      start_date: pendingDay,
      end_date: pendingDay,
      type: "pto",
      staff_message: "Daughter's graduation.",
      status: "pending",
    },
  ]);
  const morExcluded = new Set([ptoStart, ptoEnd]); // PTO days get no shifts

  // The deficiency day: Thursday of the CURRENT week at Henderson
  const gapThursday = addDaysStr(anchor, 3);

  const LOC_LINES: Record<"SV" | "HD" | "NLV", ShiftLine[]> = {
    SV: SV_LINES,
    HD: HD_LINES,
    NLV: NLV_LINES,
  };

  let totalShifts = 0;
  let deficientHours = 0;
  // Henderson's CURRENT-week period id — the override below links to it so the
  // compliance record's "Acknowledged exceptions" section surfaces on the right
  // record (the page matches override_log.target_id to the selected period).
  let henGapPeriodId: string | null = null;

  for (const offset of WEEK_OFFSETS) {
    const weekStart = addDaysStr(anchor, offset * 7);
    const weekEnd = addDaysStr(weekStart, 6);
    const dates = eachDate(weekStart, weekEnd);

    for (const loc of LOCS) {
      const { data: period, error: pErr } = await service
        .from("schedule_period")
        .insert({
          tenant_id: tenantId,
          location_id: locIds.get(loc.key)!,
          cycle: "weekly",
          start_date: weekStart,
          end_date: weekEnd,
          status: "published",
          published_at: new Date().toISOString(),
        })
        .select("id")
        .single();
      if (pErr) throw new Error(pErr.message);
      if (loc.key === "HD" && offset === 0) henGapPeriodId = period.id;

      // Build this week's shift rows from the location's recurring lines
      const shiftInputs: {
        staff: string;
        date: string;
        start: string;
        end: string;
        breakMin: number;
        workType?: string;
      }[] = [];

      for (const date of dates) {
        const day = weekday(date);
        for (const line of LOC_LINES[loc.key]) {
          if (!line.days.includes(day)) continue;
          if (line.staff === "Ashley Morales" && morExcluded.has(date)) continue;

          let { start, end } = line;
          // The Henderson story: Patel leaves at 2 PM, the float lands at 4
          if (loc.key === "HD" && date === gapThursday) {
            if (line.staff === "Dr. Sunita Patel") end = "14:00";
            if (line.staff === "Dr. Owen Fitzgerald") start = "16:00";
          }
          // Technicians need a counting work type — a typeless technician
          // does NOT count toward ratio (pharmacists count by default)
          const person = ROSTER.find((p) => p.name === line.staff)!;
          const workType =
            line.workType ??
            (person.ratio === "technician" ? "Dispensing" : undefined);
          shiftInputs.push({
            staff: line.staff,
            date,
            start,
            end,
            breakMin: line.breakMin,
            workType,
          });
        }
      }

      // Bulk insert shifts, then their segments (PostgREST preserves order)
      const { data: shifts, error: shErr } = await service
        .from("shift")
        .insert(
          shiftInputs.map((s) => ({
            tenant_id: tenantId,
            location_id: locIds.get(loc.key)!,
            staff_id: staffIds.get(s.staff)!,
            date: s.date,
            schedule_period_id: period.id,
            status: "published",
            break_minutes: s.breakMin,
            department_id: deptFor(s.staff),
          }))
        )
        .select("id");
      if (shErr) throw new Error(shErr.message);

      const { error: segErr } = await service.from("shift_segment").insert(
        shifts.map((row, i) => ({
          shift_id: row.id,
          tenant_id: tenantId,
          start_time: shiftInputs[i].start,
          end_time: shiftInputs[i].end,
          work_type_id: shiftInputs[i].workType
            ? (wtIds.get(shiftInputs[i].workType!) ?? null)
            : null,
          counts_toward_ratio: null,
        }))
      );
      if (segErr) throw new Error(segErr.message);
      totalShifts += shifts.length;

      // Compliance snapshot — same engine output the app generates at publish
      const engineSegs: EngineSegment[] = shiftInputs.map((s, i) => {
        const person = ROSTER.find((p) => p.name === s.staff)!;
        const wt = s.workType ? WORK_TYPES.find((w) => w.name === s.workType)! : null;
        return {
          shift_id: shifts[i].id,
          location_id: locIds.get(loc.key)!,
          date: s.date,
          start_time: s.start,
          end_time: s.end,
          break_minutes: s.breakMin,
          staff: { id: staffIds.get(s.staff)!, full_name: s.staff, ratio_type: person.ratio },
          work_type: wt
            ? { id: "wt", name: wt.name, counts_as: wt.counts_as as "technician" | "none", counting_default: wt.counting_default }
            : null,
          counts_override: null,
        };
      });
      const evals = evaluateZone(engineSegs, { max_techs_per_pharmacist: 3 }, 30);
      const rows = generateComplianceRecord(
        evals,
        locIds.get(loc.key)!,
        locNames.get(loc.key)!
      );
      await service.from("compliance_snapshot").insert({
        tenant_id: tenantId,
        schedule_period_id: period.id,
        location_id: locIds.get(loc.key)!,
        rows,
      });
      deficientHours += rows.filter((r) => r.ratio_status === "deficient").length;
    }
  }
  log(`${totalShifts} shifts across ${WEEK_OFFSETS.length} weeks × 3 locations.`);
  log(`${deficientHours} deficient compliance hours (expected: 2, Henderson Thursday 2–4 PM).`);

  // Document the gap the way a real pharmacy would
  const calloutAt = new Date(`${gapThursday}T20:30:00Z`); // ~1:30 PM Pacific
  await service.from("callout").insert({
    tenant_id: tenantId,
    staff_id: staffIds.get("Dr. Sunita Patel")!,
    reason:
      "Family emergency — left at 2:00 PM. Float (Dr. Fitzgerald) held at Spring Valley until 4:00 PM.",
    logged_at: calloutAt.toISOString(),
  });
  await service.from("override_log").insert({
    tenant_id: tenantId,
    actor_user_id: frankAuthId,
    target_type: "slot",
    // Link to Henderson's current-week period so the compliance record's
    // "Acknowledged exceptions" section shows it on the right record.
    target_id: henGapPeriodId ?? `${gapThursday} 14:00-16:00 Henderson`,
    warning_type: "ratio",
    reason:
      "Dr. Patel had a family emergency and left at 2:00 PM. Float pharmacist Dr. Fitzgerald was notified immediately but was held at Spring Valley until 4:00 PM. Coverage gap documented. Single isolated day — no 3-consecutive-day board notification triggered.",
  });
  await service.from("activity_log").insert({
    tenant_id: tenantId,
    actor_user_id: frankAuthId,
    action: "demo_seed",
    entity_type: "tenant",
    entity_id: tenantId,
    detail: { anchor, weeks: WEEK_OFFSETS.length, shifts: totalShifts },
  });

  return { tenantId, weeks: WEEK_OFFSETS.length, shifts: totalShifts, deficientHours };
}

/** Full reset: wipe data, re-seed, re-anchor dates to the current week. */
export async function resetMesaVista(
  service: SupabaseClient,
  log: Log = () => {}
): Promise<SeedResult> {
  const { data: tenant } = await service
    .from("tenant")
    .select("id")
    .eq("name", MESA_VISTA_NAME)
    .maybeSingle();
  if (tenant) await clearMesaVistaData(service, tenant.id, log);
  return seedMesaVista(service, log);
}
