"use client";

import { useRouter } from "next/navigation";
import Badge from "@/components/ui/badge";
import Button from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/page-header";
import {
  complianceRecordToCsv,
  SUSTAINED_DEFICIENCY_DAYS,
} from "@/lib/engine/compliance";
import { formatHourRange, formatTimestamp } from "@/lib/time-format";
import type { ComplianceRecordRow, TimeFormat } from "@/lib/types";
import type { ConstraintFlag } from "@/lib/engine/types";

/** Distinguish the two kinds of ratio deficiency for the reader. */
const FLAG_LABEL: Record<string, string> = {
  ceiling: "Over ceiling (too many techs)",
  floor: "Under floor (understaffed)",
  both: "Over ceiling + under floor",
};

export default function ComplianceView({
  periods,
  periodId,
  records,
  streaks,
  constraintFlags,
  hasRatio,
  overrides,
  tenantName,
  periodLabel,
  timeFormat,
  timezone,
}: {
  periods: { id: string; label: string }[];
  periodId: string;
  records: { locationId: string; locationName: string; rows: ComplianceRecordRow[] }[];
  streaks: {
    deficientDates: string[];
    streaks: { start: string; length: number }[];
    sustainedDeficiency: boolean;
  };
  constraintFlags: ConstraintFlag[];
  hasRatio: boolean;
  overrides: {
    id: string;
    when: string;
    warning_type: string;
    reason: string;
    actor: string;
  }[];
  tenantName: string;
  periodLabel: string;
  timeFormat: TimeFormat;
  timezone: string;
}) {
  const router = useRouter();
  const allRows = records.flatMap((r) => r.rows);
  const deficientHours = allRows.filter(
    (r) => r.ratio_status === "deficient"
  ).length;
  // A logged ratio override for this period is the documented justification for
  // its deficient hours — surface it inline on those rows so the "why" sits with
  // the hours themselves (not only in the section below / the Override Log).
  const ratioException =
    overrides.find((o) => o.warning_type === "ratio") ?? null;

  function exportCsv() {
    const blob = new Blob([complianceRecordToCsv(allRows)], {
      type: "text/csv",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `compliance-record-${periodId.slice(0, 8)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="max-w-[1100px] space-y-6 print:max-w-none">
      {/* Document header — only on the printed/PDF output. */}
      <div className="hidden print:block">
        <p className="font-brand text-lg font-bold text-navy">{tenantName}</p>
        <p className="font-brand text-base font-bold text-navy">
          Coverage Forecast — {periodLabel}
        </p>
        <p className="font-body text-xs text-steel">
          Projected hourly coverage from the published schedule. This is a
          planning forecast — the official record of what actually happened is
          the Compliance Record. Generated by RxShift.
        </p>
        <hr className="my-3 border-line" />
      </div>

      <div className="flex flex-wrap items-center gap-3 print:hidden">
        <select
          value={periodId}
          onChange={(e) =>
            router.push(`/app/coverage-forecast?period=${e.target.value}`)
          }
          className="rounded-md border-[1.5px] border-line bg-surface px-3 py-2 font-body text-sm text-navy"
        >
          {periods.map((p) => (
            <option key={p.id} value={p.id}>
              {p.label}
            </option>
          ))}
        </select>
        <div className="ml-auto flex gap-3">
          <Button variant="secondary" onClick={() => window.print()}>
            Save as PDF (forecast)
          </Button>
          <Button variant="secondary" onClick={exportCsv}>
            Export CSV (data)
          </Button>
        </div>
      </div>

      {streaks.sustainedDeficiency && (
        <div className="rounded-lg border-l-[3px] border-l-deficiency bg-deficiency-bg p-4">
          <p className="font-brand text-sm font-bold text-deficiency">
            Sustained deficiency — several consecutive deficient days
          </p>
          <p className="mt-1 font-body text-[13px] text-navy">
            {streaks.streaks
              .filter((s) => s.length >= SUSTAINED_DEFICIENCY_DAYS)
              .map((s) => `${s.length} consecutive deficient days starting ${s.start}`)
              .join("; ")}
            . This is a heads-up for your own managers. Whether and how to act
            on it is your pharmacy&rsquo;s decision — RxShift flags it and never
            contacts any board. Review the deficient hours below and the
            override log.
          </p>
        </div>
      )}

      {overrides.length > 0 && (
        <div className="rounded-lg border border-line bg-surface p-4 print:border-0 print:bg-transparent print:p-0">
          <h2 className="mb-1 font-brand text-sm font-bold text-navy">
            Acknowledged exceptions
          </h2>
          <p className="mb-3 font-body text-[12px] text-steel print:hidden">
            When this schedule was published past a compliance flag, the
            manager&rsquo;s logged reason is recorded here and travels with the
            official record.
          </p>
          <ul className="space-y-2">
            {overrides.map((o) => (
              <li key={o.id} className="font-body text-[13px] text-navy">
                <Badge tone={o.warning_type === "ratio" ? "deficiency" : "alert"}>
                  {o.warning_type}
                </Badge>{" "}
                <span className="text-steel">
                  {formatTimestamp(o.when, timezone, timeFormat)} · {o.actor}:
                </span>{" "}
                {o.reason}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Summary stats */}
      <div className="grid gap-4 sm:grid-cols-3 print:hidden">
        <Card>
          <p className="font-brand text-[10px] font-bold uppercase tracking-[1px] text-steel">
            Hours recorded
          </p>
          <p className="mt-1 font-brand text-[28px] font-bold text-navy">
            {allRows.length}
          </p>
        </Card>
        <Card>
          <p className="font-brand text-[10px] font-bold uppercase tracking-[1px] text-steel">
            Deficient hours
          </p>
          <p
            className={`mt-1 font-brand text-[28px] font-bold ${deficientHours > 0 ? "text-deficiency" : "text-compliant"}`}
          >
            {deficientHours}
          </p>
        </Card>
        <Card>
          <p className="font-brand text-[10px] font-bold uppercase tracking-[1px] text-steel">
            Hours &amp; caps flags
          </p>
          <p
            className={`mt-1 font-brand text-[28px] font-bold ${constraintFlags.length > 0 ? "text-alert" : "text-compliant"}`}
          >
            {constraintFlags.length}
          </p>
        </Card>
      </div>

      {!hasRatio && (
        <p className="font-body text-sm text-steel">
          Your organization has no ratio requirement configured — this forecast
          projects staffing presence. Enable the ratio in Settings to add
          compliant/deficient evaluation.
        </p>
      )}

      {records.length === 0 ? (
        <EmptyState message="No shifts in this period yet. Schedule shifts for them to appear on the record." />
      ) : (
        records.map((record) => (
          <div key={record.locationId}>
            <h2 className="mb-3 font-brand text-base font-bold text-navy">
              {record.locationName}
            </h2>
            <div className="overflow-x-auto rounded-[10px] border border-line bg-surface shadow-[0_1px_3px_rgba(28,47,94,0.08)]">
              <table className="w-full">
                <thead>
                  <tr>
                    {[
                      "Date",
                      "Hour",
                      "Pharmacist(s) on duty",
                      "Technicians counting",
                      "Present, not counting (function)",
                      "Status",
                    ].map((h) => (
                      <th
                        key={h}
                        className="bg-cloud px-3 py-2.5 text-left font-brand text-[9.5px] font-bold uppercase tracking-[1px] text-steel"
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {record.rows.map((r, i) => (
                    <tr
                      key={i}
                      className={
                        r.ratio_status === "deficient" ? "bg-deficiency-bg" : ""
                      }
                    >
                      <td className="border-t border-line px-3 py-2 font-brand text-[11px] font-semibold text-steel">
                        {r.date}
                      </td>
                      <td className="border-t border-line px-3 py-2 font-brand text-[11px] font-semibold text-steel">
                        {formatHourRange(r.hour, timeFormat)}
                      </td>
                      <td className="border-t border-line px-3 py-2 font-body text-[13px] font-medium text-navy">
                        {r.pharmacists_on_duty.join(", ") || "—"}
                      </td>
                      <td className="border-t border-line px-3 py-2 font-body text-[13px] text-navy">
                        {(r.technicians_counting as string[]).join(", ") || "—"}
                        {r.technicians_count > 0 && (
                          <span className="ml-1 text-steel">
                            ({r.technicians_count})
                          </span>
                        )}
                      </td>
                      <td className="border-t border-line px-3 py-2 font-body text-[13px] text-steel">
                        {r.technicians_present_non_counting.length > 0
                          ? r.technicians_present_non_counting
                              .map((t) => `${t.name} (${t.function})`)
                              .join(", ")
                          : "—"}
                      </td>
                      <td className="border-t border-line px-3 py-2">
                        <Badge
                          tone={
                            r.ratio_status === "deficient"
                              ? "deficiency"
                              : "compliant"
                          }
                        >
                          {r.ratio_status}
                        </Badge>
                        {r.flag_type && FLAG_LABEL[r.flag_type] && (
                          <span className="ml-1.5 font-brand text-[10px] font-bold uppercase tracking-[0.5px] text-deficiency">
                            {FLAG_LABEL[r.flag_type]}
                          </span>
                        )}
                        {r.deficiency_reason && (
                          <p className="mt-1 font-body text-[11px] text-deficiency">
                            {r.deficiency_reason}
                          </p>
                        )}
                        {r.ratio_status === "deficient" && ratioException && (
                          <p className="mt-1.5 max-w-[280px] font-body text-[11px] leading-snug text-alert">
                            <span className="font-brand font-bold uppercase tracking-[0.5px]">
                              ⚠ Acknowledged exception
                            </span>{" "}
                            <span className="text-steel">
                              ({ratioException.actor}):
                            </span>{" "}
                            {ratioException.reason}
                          </p>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        ))
      )}

      {constraintFlags.length > 0 && (
        <div>
          <h2 className="mb-3 font-brand text-base font-bold text-navy">
            Hours &amp; caps exceptions
          </h2>
          <Card>
            <ul className="space-y-2 font-body text-[13px] text-navy">
              {constraintFlags.map((f, i) => (
                <li key={i}>
                  <Badge tone="alert">{f.rule_type.replace(/_/g, " ")}</Badge>{" "}
                  <span className="ml-1">{f.message}</span>
                </li>
              ))}
            </ul>
          </Card>
        </div>
      )}

      <p className="font-body text-xs text-steel print:hidden">
        This forecast regenerates from the current published schedule. The
        immutable record of what actually happened (retained two years) is the{" "}
        <a href="/app/log" className="underline">
          Compliance Record
        </a>
        ; acknowledged warnings are in the{" "}
        <a href="/app/log/overrides" className="underline">
          override log
        </a>
        .
      </p>
    </div>
  );
}
