"use client";

// The Compliance Record (as-worked): the IMMUTABLE, hour-by-hour record of what
// ACTUALLY happened at each location. Rows are never edited — a manager adds an
// after-the-fact note to explain an hour (the determination stands). Mirrors the
// audit-log note pattern.

import { useState } from "react";
import { useRouter } from "next/navigation";
import Badge from "@/components/ui/badge";
import Button from "@/components/ui/button";
import Modal from "@/components/ui/modal";
import { Label, Textarea, HelpText } from "@/components/ui/form";
import { complianceRecordToCsv } from "@/lib/engine/compliance";
import { appendComplianceNote } from "@/lib/actions/compliance-notes";
import { formatHourRange } from "@/lib/time-format";
import type { ComplianceRecordRow, TimeFormat } from "@/lib/types";

export interface RecordHour {
  id: string;
  hour: number;
  ratio_status: "compliant" | "deficient";
  deficiency_reason: string | null;
  detail: ComplianceRecordRow;
  notes: { id: string; note: string; author: string; created_at: string }[];
}

/** Distinguish the two kinds of ratio deficiency for the reader. */
const FLAG_LABEL: Record<string, string> = {
  ceiling: "Over ceiling (too many techs)",
  floor: "Under floor (understaffed)",
  both: "Over ceiling + under floor",
};
export interface RecordLocation {
  locationId: string;
  locationName: string;
  hours: RecordHour[];
}

export default function ComplianceRecordView({
  dates,
  selectedDate,
  records,
  tenantName,
  timeFormat,
}: {
  dates: string[];
  selectedDate: string;
  records: RecordLocation[];
  tenantName: string;
  timeFormat: TimeFormat;
}) {
  const router = useRouter();
  const [noteFor, setNoteFor] = useState<RecordHour | null>(null);
  const [note, setNote] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const allRows = records.flatMap((r) => r.hours.map((h) => h.detail));
  const deficientHours = allRows.filter((r) => r.ratio_status === "deficient").length;

  function exportCsv() {
    const blob = new Blob([complianceRecordToCsv(allRows)], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `compliance-record-${selectedDate}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function saveNote() {
    if (!noteFor || note.trim().length === 0) return;
    setBusy(true);
    setError(null);
    const res = await appendComplianceNote({
      compliance_record_id: noteFor.id,
      note: note.trim(),
    });
    if (res.ok) {
      setNoteFor(null);
      setNote("");
      router.refresh();
    } else {
      setError(res.error ?? "Something went wrong.");
    }
    setBusy(false);
  }

  const hr = (h: number) => formatHourRange(h, timeFormat);

  return (
    <div className="max-w-[1100px] space-y-6 print:max-w-none">
      {/* Official document header — printed/PDF only. */}
      <div className="hidden print:block">
        <p className="font-brand text-lg font-bold text-navy">{tenantName}</p>
        <p className="font-brand text-base font-bold text-navy">
          Compliance Record — {selectedDate}
        </p>
        <p className="font-body text-xs text-steel">
          Official, immutable record of actual hourly staffing &amp; ratio
          compliance. Notes are appended, never edited. Generated by RxShift.
        </p>
        <hr className="my-3 border-line" />
      </div>

      <div className="rounded-lg border-l-[3px] border-l-navy bg-cloud/60 p-4 print:hidden">
        <p className="font-body text-[13px] leading-relaxed text-navy">
          The <span className="font-bold">Compliance Record</span> is the
          immutable, hour-by-hour record of what <em>actually happened</em> —
          reconstructed from the published schedule and your team&rsquo;s live
          statuses as each hour passed, then frozen. It is{" "}
          <span className="font-bold">never edited</span>; to explain an hour
          (e.g. a documented coverage gap), add a note. Retained two years.
          Looking ahead instead?{" "}
          <a href="/app/coverage-forecast" className="underline">
            Coverage Forecast
          </a>{" "}
          projects the published schedule.
        </p>
      </div>

      <div className="flex flex-wrap items-center gap-3 print:hidden">
        <select
          value={selectedDate}
          onChange={(e) => router.push(`/app/log?date=${e.target.value}`)}
          className="rounded-md border-[1.5px] border-line bg-surface px-3 py-2 font-body text-sm text-navy"
        >
          {dates.map((d) => (
            <option key={d} value={d}>
              {d}
            </option>
          ))}
        </select>
        <div className="ml-auto flex gap-3">
          <Button variant="secondary" onClick={() => window.print()}>
            Save as PDF (official record)
          </Button>
          <Button variant="secondary" onClick={exportCsv}>
            Export CSV (data)
          </Button>
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 print:hidden">
        <div className="rounded-[10px] border border-line bg-surface p-4">
          <p className="font-brand text-[10px] font-bold uppercase tracking-[1px] text-steel">
            Hours recorded ({selectedDate})
          </p>
          <p className="mt-1 font-brand text-[28px] font-bold text-navy">
            {allRows.length}
          </p>
        </div>
        <div className="rounded-[10px] border border-line bg-surface p-4">
          <p className="font-brand text-[10px] font-bold uppercase tracking-[1px] text-steel">
            Deficient hours
          </p>
          <p
            className={`mt-1 font-brand text-[28px] font-bold ${deficientHours > 0 ? "text-deficiency" : "text-compliant"}`}
          >
            {deficientHours}
          </p>
        </div>
      </div>

      {records.length === 0 ? (
        <p className="font-body text-sm text-steel">
          No hours recorded for {selectedDate} yet. Hours are finalized after
          they pass.
        </p>
      ) : (
        records.map((rec) => (
          <div key={rec.locationId}>
            <h2 className="mb-3 font-brand text-base font-bold text-navy">
              {rec.locationName}
            </h2>
            <div className="overflow-x-auto rounded-[10px] border border-line bg-surface shadow-[0_1px_3px_rgba(28,47,94,0.08)]">
              <table className="w-full">
                <thead>
                  <tr>
                    {[
                      "Hour",
                      "Pharmacist(s) on duty",
                      "Technicians counting",
                      "Present, not counting",
                      "Status",
                      "",
                    ].map((h) => (
                      <th
                        key={h}
                        className="bg-cloud px-3 py-2.5 text-left font-brand text-[9.5px] font-bold uppercase tracking-[1px] text-steel"
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {rec.hours.map((h) => (
                    <tr
                      key={h.id}
                      className={h.ratio_status === "deficient" ? "bg-deficiency-bg" : ""}
                    >
                      <td className="border-t border-line px-3 py-2 align-top font-brand text-[11px] font-semibold text-steel">
                        {hr(h.hour)}
                      </td>
                      <td className="border-t border-line px-3 py-2 align-top font-body text-[13px] font-medium text-navy">
                        {h.detail.pharmacists_on_duty.join(", ") || "—"}
                      </td>
                      <td className="border-t border-line px-3 py-2 align-top font-body text-[13px] text-navy">
                        {(h.detail.technicians_counting as string[]).join(", ") || "—"}
                        {h.detail.technicians_count > 0 && (
                          <span className="ml-1 text-steel">
                            ({h.detail.technicians_count})
                          </span>
                        )}
                      </td>
                      <td className="border-t border-line px-3 py-2 align-top font-body text-[13px] text-steel">
                        {h.detail.technicians_present_non_counting.length > 0
                          ? h.detail.technicians_present_non_counting
                              .map((t) => `${t.name} (${t.function})`)
                              .join(", ")
                          : "—"}
                      </td>
                      <td className="border-t border-line px-3 py-2 align-top">
                        <Badge
                          tone={h.ratio_status === "deficient" ? "deficiency" : "compliant"}
                        >
                          {h.ratio_status}
                        </Badge>
                        {h.detail.flag_type && FLAG_LABEL[h.detail.flag_type] && (
                          <span className="ml-1.5 font-brand text-[10px] font-bold uppercase tracking-[0.5px] text-deficiency">
                            {FLAG_LABEL[h.detail.flag_type]}
                          </span>
                        )}
                        {h.deficiency_reason && (
                          <p className="mt-1 font-body text-[11px] text-deficiency">
                            {h.deficiency_reason}
                          </p>
                        )}
                        {h.notes.length > 0 && (
                          <ul className="mt-1.5 space-y-1 border-l-2 border-amber/40 pl-2.5">
                            {h.notes.map((n) => (
                              <li
                                key={n.id}
                                className="font-body text-[11px] leading-snug text-steel"
                              >
                                <span className="font-semibold text-navy">
                                  Note
                                </span>{" "}
                                · {n.author} ·{" "}
                                {new Date(n.created_at).toLocaleDateString()}:{" "}
                                {n.note}
                              </li>
                            ))}
                          </ul>
                        )}
                      </td>
                      <td className="border-t border-line px-3 py-2 align-top print:hidden">
                        <button
                          onClick={() => {
                            setNoteFor(h);
                            setNote("");
                            setError(null);
                          }}
                          className="rounded border border-line px-2.5 py-1 font-brand text-[11px] font-semibold text-navy hover:border-amber"
                        >
                          + Note
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        ))
      )}

      <Modal
        open={noteFor !== null}
        onClose={() => {
          setNoteFor(null);
          setNote("");
        }}
        title="Add a note to this hour"
        footer={
          <>
            <Button
              variant="secondary"
              onClick={() => {
                setNoteFor(null);
                setNote("");
              }}
            >
              Cancel
            </Button>
            <Button onClick={saveNote} disabled={busy || note.trim().length === 0}>
              {busy ? "Saving…" : "Add note"}
            </Button>
          </>
        }
      >
        {noteFor && (
          <div className="space-y-3">
            <p className="font-body text-sm text-steel">
              {selectedDate} · {hr(noteFor.hour)} ·{" "}
              <span
                className={
                  noteFor.ratio_status === "deficient"
                    ? "font-medium text-deficiency"
                    : "text-navy"
                }
              >
                {noteFor.ratio_status}
              </span>
            </p>
            <div>
              <Label htmlFor="rec-note">Note</Label>
              <Textarea
                id="rec-note"
                rows={3}
                value={note}
                onChange={(e) => setNote(e.target.value)}
                placeholder="e.g. Dr. Patel left at 2pm — family emergency; float held at Spring Valley until 4pm. Coverage gap documented."
              />
              <HelpText>
                The record is never changed — your note is appended and
                attributed to you.
              </HelpText>
            </div>
            {error && <p className="font-body text-sm text-deficiency">{error}</p>}
          </div>
        )}
      </Modal>
    </div>
  );
}
